export const phrases = [
    "Really? Please, tell me more!",
    "That sounds like a tough one...",
    "Did you check the console?",
    "What do you think you should try next?",
    "What would Kevin Powell do?",
    "Have you tried turning it off and on again?",
    "I wonder if Google has an answer...",
    "Hmm, interesting. What's your gut feeling on this?",
    "Could you elaborate a bit further?",
    "Ah, the classic developer dilemma.",
    "I sense a challenge here. How can we tackle it?",
    "Are there any error messages to guide us?",
    "Let's explore this together, shall we?",
    "I'm intrigued. What's your intuition telling you?",
    "Let's take a step back. What's the big picture?",
    "Time for a brainstorm. What are your options?",
    "Sometimes, it's the small things. Anything you might have missed?",
    "The code gods can be mysterious. Any sacrifices made?",
    "Have you considered consulting the ancient scrolls of Stack Overflow?",
    "Coding, a journey of endless possibilities.",
    "Let's channel our inner debugger and investigate.",
    "This feels like a quest. What's your next move, adventurer?",
    "Have you whispered to the code gently? It might reveal its secrets.",
    "Have you explored the dark corners of documentation?",
    "In the realm of programming, patience is often a virtue.",
    "Are you ready to embark on a code crusade?",
    "Sometimes, code speaks in riddles. What's its message?"
];
