export const phrases = [
    "Really? Please, tell me more!",
    "That sounds like a tough one...",
    "Did you check the console?",
    "What do you think you should try next?",
    "What would Kevin Powell do?",
    "Have you tried turning it off and on again?",
    "I wonder if Google has an answer...",
    "Hmm, interesting. What's your gut feeling on this?",
    "Could you elaborate a bit further?",
    "Ah, the classic developer dilemma.",
    "I sense a challenge here. How can we tackle it?",
    "Are there any error messages to guide us?",
    "Let's explore this together, shall we?",
    "I'm intrigued. What's your intuition telling you?",
    "Let's take a step back. What's the big picture?",
    "Time for a brainstorm. What are your options?",
    "Sometimes, it's the small things. Anything you might have missed?",
    "The code gods can be mysterious. Any sacrifices made?",
    "Have you considered consulting the ancient scrolls of Stack Overflow?",
    "Coding, a journey of endless possibilities.",
    "Let's channel our inner debugger and investigate.",
    "This feels like a quest. What's your next move, adventurer?",
    "Have you whispered to the code gently? It might reveal its secrets.",
    "Have you explored the dark corners of documentation?",
    "In the realm of programming, patience is often a virtue.",
    "Are you ready to embark on a code crusade?",
    "Sometimes, code speaks in riddles. What's its message?"
];

export const silent_phrases = [
    "Silence speaks volumes, doesn't it?",
    "Cat got your keyboard?",
    "I'm here whenever you're ready to chat.",
    "Don't be shy, feel free to ask anything.",
    "Is there something on your mind, or did you just enjoy the silence?",
    "No worries, take your time.",
    "Feel free to type whenever you're ready.",
    "I'll be right here when you have a question or need assistance.",
    "Just hanging out in the digital void. Let me know if you need anything.",
    "The silence is deafening. How can I assist you today?",
    "Need a moment to gather your thoughts?",
    "Did I stump you with my previous response?",
    "Hello? Is it code you're looking for?",
    "I'm patiently waiting for your input.",
    "It's all quiet on the digital front. What's on your mind?"
]

export const you_phrases = [
    "Who, me? I'm just a frog silly!",
    "Ah, you've noticed! What can I assist you with today?",
    "You're right, I'm here to help. How can I assist you?",
    "You're quite observant! How can I be of service?",
    "Yes, you're chatting with me! What's on your mind?",
    "It's all about you! How can I assist you further?",
    "You're the star of this conversation. What can I do for you?",
    "You've got my attention! How can I assist you today?",
    "You're absolutely correct! How may I assist you?",
    "Indeed, you're chatting with me. How can I help?",
    "You've found your way here! What can I do for you?"
]